### PR TITLE
OpenBLAS v0.3.21

### PR DESCRIPTION
**Pull request by tjhei**

### CODE REVIEW

**Comment by tjhei** [comment]
maybe worth trying on Stampede, @naliboff @MFraters

**Comment by MFraters** [comment]
Thanks! Will try it once stampede is working again :)

**Comment by MFraters** [comment]
I tested it and openblas v0.3.21 didn't compile on on stampede with candi.

**Comment by tjhei** [comment]
This helps building on ARM, so let's merge.

**Pull request merged**
