### PR TITLE
use Trilinos explicit instantiations

### PR DESCRIPTION
**Pull request by tjhei**

### CODE REVIEW

**Comment by koecher** [comment]
May you shortly explain why we need this switch?

**Comment by tjhei** [comment]
faster compile times, lower memory requirement and compile time. See https://github.com/dealii/dealii/issues/1643

**Comment by koecher** [comment]
Ah looks good.
When I've read this correctly, it should not break the compilation since we are only using superlu_dist with amesos and not with amesos2. But I will try this if it is really working.

**Comment by koecher** [comment]
Unfortunately, if this switch is enabled, then Amesos2 (needed by MueLu) catches SuperLU and the compilation breaks. The code block
```
if [ -z "${SUPERLU_DIR}" ]; then
    CONFOPTS="\
        ${CONFOPTS} \
          -D Trilinos_ENABLE_EXPLICIT_INSTANTIATION=ON "
fi
```
after the `General Trilinos configuration` configuration works for me.

**Comment by tjhei** [comment]
It is enough to disable amesos2 (which is not used by deal.II anyways as far as I can tell). Would that be a better solution?

**Comment by koecher** [comment]
I tried this as the simplest solution, but unfortunately, Amesos2 is used by MueLu. So disabling does not work for me.

**Comment by koecher** [comment]
I think the code block from my comment (20th May) should work best for now.

**Comment by koecher** [comment]
the issue will be resolved with PR #10

**Pull request closed without merging**
