### PR TITLE
Say what option it is that isn't recognized.

### PR DESCRIPTION
**Pull request by bangerth**
Replacement for #228, now against master.

### CODE REVIEW

**Comment by koecher** [comment]
@bangerth Thank you!

**Comment by koecher** [comment]
@bangerth and sorry for the clash for the PR strategy.

We need to set up how this repo is working/rules for development, esp. if more than Timo and I working on that.

**Comment by bangerth** [comment]
You've been doing an excellent job, and I've got no problem letting you figure out what branch strategy works best for you.

I'm just happy to have had my first candi patch accepted :-)

**Comment by koecher** [comment]
> You've been doing an excellent job, and I've got no problem letting you figure out what branch strategy works best for you.
> 
> 
> 
> I'm just happy to have had my first candi patch accepted :-)

Thanks and you are very welcome to push more if you have any trouble or ideas with your installation of a deal.II based toolchain ;-)

**Pull request merged**
