### PR TITLE
sundials: enable optimizations, disable examples

### PR DESCRIPTION
**Pull request by tjhei**
FYI @gassmoeller

### CODE REVIEW

**Review by bangerth — APPROVED** [review]

**Review by gassmoeller — APPROVED** [review]
Yes! We see improvements in the performance of about 50%.

**Comment by bangerth** [comment]
That's pretty nice!

**Comment by gassmoeller** [comment]
I would merge, but it looks like the jenkins tester had problems.

**Comment by tjhei** [comment]
tester is broken right now.

**Pull request merged**
