### PR TITLE
preliminary mac osx support

### PR DESCRIPTION
**Pull request by tjhei**
- add detection for OSX and shows a temporary platform info
- remove nano-second timing computation because it is broken on mac

note: not all packages are working correctly but some do.

### CODE REVIEW

**Comment by koecher** [comment]
Well, last week I got my first macbook. I'll check that as soon as possible.
I think we should develop this feature in a special branch, not on master.
What do you mean by "not all packages are working correctly", do they compile but do not work as expected?

**Comment by tjhei** [comment]
> I think we should develop this feature in a special branch

I think this PR is certainly an improvement and self-contained so there is no risk in merging it. The next thing is getting all packages to work and we can do that on a branch.

> What do you mean by "not all packages are working correctly", do they compile but do not work as expected?

p4est and trilinos work, opencascade release 0.17 and 0.18 fail (but master works), I have not tested anything else so far. It also depends on how you set up your system of course. I am currently using gcc, openmpi, bash, cmake compiled using homebrew, because that is what we want to use when packaging deal.II on the mac.

**Comment by koecher** [comment]
is the open-mpi from homebrew is compiled against the gcc-6 from homebrew?

**Comment by tjhei** [comment]
> is the open-mpi from homebrew is compiled against the gcc-6 from homebrew?

My current process: compile gcc and openmpi using default compilers, then set the wrapper to use gcc (I couldn't compile openmpi successfully with gcc):
```
git clone https://github.com/Homebrew/brew.git $BREWDIR
export PATH=$BREWDIR/bin:$PATH
export HOMEBREW_BUILD_FROM_SOURCE=1
brew tap homebrew/science
brew install --build-bottle ninja cmake gcc openmpi
export OMPI_CXX=g++-6
export OMPI_CC=gcc-6

git clone https://github.com/dealii/candi.git
cd candi
./candi.sh -j 2 --packages="p4est trilinos" -p $BREWDIR/
```

**Comment by koecher** [comment]
Okay, have the same issue here, something makes an seg. fault for open-mpi v2.1.0 if compiled against gcc-6. Looks like a prominent error in brew.

**Comment by tjhei** [comment]
Yes, but using gcc is "unsupported" so they are not interested in fixing it. It seems that compiling with clang and then switching to wrap gcc works fine though.

**Pull request merged**
