### PR TITLE
enable fpic in parmetis to support clang

### PR DESCRIPTION
**Pull request by tjhei**
This works with gcc and clang on ubuntu 14 at least.

### CODE REVIEW

**Comment by koecher** [comment]
looks good, but since this is compiled via an C++ compiler, would it make sense to set also `CXXFLAGS` or `CPPFLAGS`?

**Comment by tjhei** [comment]
Well, it doesn't compile before and it works with this change. Why should I change other flags?

**Comment by koecher** [comment]
This is a bit curious, I compiled metis/parmetis several times with clang without that problem. Maybe the default compiler flags are different on RedHat based systems.
Anyhow, you are using a C compiler flag to be handed over to a C++ compiler. This could bring us in trouble in future or on other systems.
I would suggest, that you test this with `CPPFLAGS` (at least gcc is using this variable for both, gcc and g++ as far as I know). If it works, we should use that variable.

**Comment by koecher** [comment]
is this still needed? (currently we have a merge confict on the parmetis package)
If not, I would like to reject this PR.

**Pull request closed without merging**
