### PR TITLE
OSX 10.14 and 10.15 support

### LINKED ISSUE #130: test on OSX Mojave and Catalina
based on discussion in #128

### PR DESCRIPTION
**Pull request by tjhei**
- add platform detection
- update homebrew instructions
- fixes #130

### CODE REVIEW

**Comment by tjhei** [comment]
I have not tested 10.14 but 10.15 seems to work (at least a minimal build). I will post other separate PRs if I find other problems.

**Comment by tjhei** [comment]
Let me know if I should push this to the 9.1 branch as well. I assume the answer is yes. :-)

**Comment by koecher** [comment]
Hei @tjhei, yes pushing to 9.1 sounds good.

**Comment by tjhei** [comment]
> Hei @tjhei, yes pushing to 9.1 sounds good.

done.

**Pull request merged**
