### PR TITLE
update Trilinos to 13.2

### PR DESCRIPTION
**Pull request by tjhei**
- Trilinos 13.2.0
- Enable explicit instantiations #231

This fixes compilation on Ubuntu 22.04

### CODE REVIEW

**Comment by tjhei** [comment]
fixes #252

**Comment by kinnewig** [comment]
I am already using deal.II with Trilinos 13.2.0 (because I need a certain feature, that is only available in Trilinos >= 13).

But tpetra and muelu are not usable in deal.II with Trilinos >=13. Since the test "Performing Test TRILINOS_TPETRA_IS_FUNCTIONAL" fails, therefore also the test "TRILINOS_MUELU_IS_FUNCTIONAL" fails, as muelu is used through tpetra in deal.II.

I just tested these changes and both tests also failed (see below).

So far I have not found the origin of this problem.

`-- Found TRILINOS
-- Checking whether the found trilinos package contains all required modules:
--   Found Amesos
--   Found Epetra
--   Found Ifpack
--   Found AztecOO
--   Found Teuchos
--   Found ML
--   Found EpetraExt
--   Found Kokkos
--   Found MueLu
--   Found ROL
--   Found Sacado
--   Module SEACAS not found!
--   Found Tpetra
--   Found Zoltan
--   Found MUMPS
-- Looking for KOKKOS_ENABLE_CUDA
-- Looking for KOKKOS_ENABLE_CUDA - not found
-- Looking for KOKKOS_ENABLE_CUDA_LAMBDA
-- Looking for KOKKOS_ENABLE_CUDA_LAMBDA - not found
-- Performing Test TRILINOS_TPETRA_IS_FUNCTIONAL
-- Performing Test TRILINOS_TPETRA_IS_FUNCTIONAL - Failed
-- Tpetra was found but is not usable! Disabling Tpetra support.
-- Performing Test TRILINOS_MUELU_IS_FUNCTIONAL
-- Performing Test TRILINOS_MUELU_IS_FUNCTIONAL - Failed
-- MueLu was found but is not usable through Epetra! Disabling MueLu support.
-- Found SACADO_CONFIG_H
-- Found SACADO_TRAD_HPP
-- Performing Test TRILINOS_CXX_SUPPORTS_SACADO_COMPLEX_RAD
-- Performing Test TRILINOS_CXX_SUPPORTS_SACADO_COMPLEX_RAD - Success
-- DEAL_II_WITH_TRILINOS successfully set up with external dependencies.
`

**Comment by Rombur** [comment]
deal.II does not support Tpetra when using Trilinos 13.2 see https://github.com/dealii/dealii/pull/13973

> muelu is used through tpetra in deal.II.

This is not true. The error message you posted clearly says that we are using the Epetra backend from MueLU ` MueLu was found but is not usable through Epetra!` The problem is that MueLU used to support both Epetra and Tpetra at the same time. Then they decided that if Tpetra was enabled, MueLU would not support Epetra.  deal.II uses the Epetra wrappers  from MueLU and so there is a compatibility problem. If you enable Tpetra, you cannot use MueLU.

**Comment by tjhei** [comment]
I played a little bit with this, but I can not compile trilinos 13.2 with tpetra disabled:
```
/home/heister/candi-tmp/tmp/unpack/Trilinos-trilinos-release-13-2-0/packages/xpetra/src/FakeKokkos/Kokkos_ConfigDefs.hpp:50:10: fatal error: KokkosCompat_ClassicNodeAPI_Wrapper.hpp: No such file or directory
   50 | #include <KokkosCompat_ClassicNodeAPI_Wrapper.hpp>
```
 Unfortunately, this means we can not use Muelu in the current configuration.

**Comment by tjhei** [comment]
Regardless, we should merge this PR...

**Comment by tjhei** [comment]
(cherrypicked to 9.4 branch)

**Pull request merged**
