### PR TITLE
Remove unused file default.packages

### PR DESCRIPTION
**Pull request by gfcas**
@koecher Do we need this file really? Or what was the intention?

### CODE REVIEW

**Comment by koecher** [comment]
I'm not sure why we have this file. I'll check this again but I think we don't need this

**Comment by tjhei** [comment]
used here:
https://github.com/dealii/candi/blob/a0ab3ba1100bb1483bfa39351108e7d97173a032/candi.sh#L815-L821

Not sure what this does. Can be deleted, I think.

**Comment by koecher** [comment]
@tjhei Thanks for finding this. I think this goes down to the initial commits of this feature. We need to deep-check this.

**Comment by tjhei** [comment]
Well, packages are always set in the .cfg, so this block of code can be deleted as well.

**Comment by koecher** [comment]
@gfcas can you add the code deletion in you PR as well?

**Comment by gfcas** [comment]
Of course ... deleted

**Review by tjhei — APPROVED** [review]

**Review by koecher — APPROVED** [review]

**Pull request merged**
