### PR TITLE
[9.2] take over recently merged PRs

### PR DESCRIPTION
**Pull request by tjhei**
take over #137 #136 #140 to the new 9.2 branch

### CODE REVIEW

**Comment by koecher** [comment]
hmpf. we have an build error for step-70 for OSX parallel. and some maybe other build error for OSX (I can't see the log, but I think it could be the same issue).

**Comment by tjhei** [comment]
yeah, this is a bug fixed in https://github.com/dealii/dealii/pull/10269

**Comment by tjhei** [comment]
also added #141

**Comment by tjhei** [comment]
works now.

**Pull request merged**
