### PR TITLE
Add option to skip prompts

### PR DESCRIPTION
**Pull request by gfcas**
Resubmit of skip prompts option to the master branch.

### CODE REVIEW

**Comment by gfcas** [comment]
I just realize, that maybe an entry to the readme would be also helpful?!

**Comment by koecher** [comment]
thanks. Once the tester is happy it can be merged.

**Review by tjhei — APPROVED** [review]
very nice, I wanted to have that option myself before.

**Comment by tjhei** [comment]
The test failure is unrelated and probably requires fixing the setup.

**Comment by koecher** [comment]
> very nice, I wanted to have that option myself before.

Same for me but didn’t find the time to do this.

Thank you @gfcas once again.

**Pull request merged**
