### PR TITLE
switch cmake to 3.10.1

### PR DESCRIPTION
**Pull request by tjhei**

### CODE REVIEW

**Comment by bangerth** [comment]
Does cmake 3.10.1 now work with MPI? See https://github.com/dealii/dealii/issues/5510

**Comment by tjhei** [comment]
Well, good point. I wanted an easy way to install the newest cmake but breaking the install is probably not a good idea. Hrm. Maybe we should leave this open for now.

**Comment by koecher** [comment]
is there any good news on cmake 3.10.1?

**Comment by tjhei** [comment]
I think the status is 3.10 works with the current dev version but not with deal 8.5.1. So our options are a) wait until 9.0 is done (soon!), b) release 8.5.2 with a cmake fix (unlikely).

**Comment by koecher** [comment]
Okay, but my current workstation (fedora 26) currently ships cmake 3.10.1. Maybe a fix for deal.II is not the worst idea. Haven't compiled deal.II for some time, but I think I would hit the cmake problem. Other distros might have it also.
The next deal.II version will be a major change. I think a lot of things need to be reimplemented to catch the new or changed interfaces and behaviours. So it would be good, if one could go back one version without having trouble with the system environment.

**Comment by bangerth** [comment]
I guess that would require @tamiko to backport the changes made to accommodate the new `FindMPI` module to 8.5.x. @tamiko, what's your opinion on this?

**Comment by tjhei** [comment]
Worst case would be to manually install an older cmake version if you want to stay on 8.5.0.

**Comment by koecher** [comment]
Currently candi ships version 3.4. of cmake, but not as default. Maybe we could also patch the package file of deal.II (v8.5) and set a warning, if cmake 3.10 is present...

**Pull request closed without merging**
