### PR TITLE
Takeover 267 289

### LINKED ISSUE #292: Takeover PRs
Sorry, I am a bit confused. Are the PR #267 and #289 are already merged into master? For me they seem to be only merged into deali-9.3...

### PR DESCRIPTION
**Pull request by koecher**
resolves #292 by taking over commits from dealii-9.3 branch to the master branch.

### CODE REVIEW

**Comment by koecher** [comment]
@gfcas here you see the progress for merging the requested PRs / Commits into master

**Comment by gfcas** [comment]
> @gfcas here you see the progress for merging the requested PRs / Commits into master

Thanks @koecher !

**Comment by tjhei** [comment]
what was the issue with #290 and #291?

**Comment by gfcas** [comment]
I am very sorry! I looked through the git log history searching for '267' and '289' in the commit message without finding them...

**Pull request merged**
