### PR TITLE
major platform update; adds platforms debian9 and ubuntu17

### PR DESCRIPTION
**Pull request by koecher**
majorly updated the platforms and their recognition
* simplifies ```guess_ostype``` and ```guess_platform```
* adds the platform debian9 which was reported to work by Lukas van de Wiel
* adds the platform ubuntu17 which was reported to work by Lukas van de Wiel
* deprecates fedora22 and fedora23 (not supported anymore by redhat)

### CODE REVIEW

**Comment by tjhei** [comment]
I am confused by your ubuntu versioning scheme. There are always two releases a year .04 and .10. Your current approach doesn't detect 16.10 or 17.10, right? See https://wiki.ubuntu.com/Releases

**Comment by koecher** [comment]
@tjhei I'm not working on ubuntu.
It looks like nobody has faced the issue for the x.10 versions, but you are right.
Is there a better way to recognize ubuntu?

**Comment by tjhei** [comment]
``lsb_release -r -s`` should just return the version number

**Comment by koecher** [comment]
a cool - works even on fedora

**Comment by koecher** [comment]
@tjhei does this work on ubuntu?

**Comment by tjhei** [comment]
> @tjhei does this work on ubuntu?

No, because it returns the full version number (for example "14.04" for my machine). Do we want to have separate platforms for the .04 and .10 release?

**Comment by koecher** [comment]
I think that's not necessary today, or are the basic install instruction that different between two versions?

**Comment by koecher** [comment]
okay, does: ``` lsb_release -r -s |grep -o -E '[0-9]+' |head -n 1 ``` this output give only the first number?

**Comment by tjhei** [comment]
> I think that's not necessary today, or are the basic install instruction that different between two versions?

Well, you would group every other version together into a single file. We certainly have different instructions for those, right? I don't know if we want different versions for 17.04 and 17.10 for example, 17.10 is not released yet after all.

> okay, does: lsb_release -r -s |grep -o -E '[0-9]+' |head -n 1 this output give only the first number?

Yes, returns "14".

**Comment by koecher** [comment]
I think nowadays there are not that much different intructions between 2-yearly released OS.
I've updated and simplified that. Works on fedora (has only one number, centos 7.x.xxxx and rhel 7.x.xxxx).

**Comment by koecher** [comment]
When looking in detail to the platform files, only ubuntu12 had now a specific instruction (because of an old deal.II 8.3 together with trilinos 12 which was not working).

**Comment by koecher** [comment]
ready to merge? anything else to do?

**Comment by tjhei** [comment]
I think this is good enough. If we need special instructions for a non-LTS version, we can always add a special case then.

**Pull request merged**
