### PR TITLE
fix bug on metis installation when USE_64_BIT_INDICES=ON

### PR DESCRIPTION
**Pull request by Wendi-L**
# Description of the problem

- When "USE_64_BIT_INDICES=ON" and install both ParMETIS & PETSc, The installation will be stopped with an error as shown below from the PETSc:
```
==============
Configuring PETSc to compile on your system                            
==============

==============
UNABLE to CONFIGURE with GIVEN OPTIONS    (see configure.log for details):
==============

Metis specified is incompatible!

--with-64-bit-indices option requires a metis build with IDXTYPEWIDTH=64.
Suggest using --download-metis for a compatible metis
```
- After checking, it is the Line33 & Line 43 of "*/parmetis-4.0.3/metis/include/metis.h" that still keep
```
#define IDXTYPEWIDTH 32
```
& 
```
#define REALTYPEWIDTH 32
```

# Description of the solution

- Add an "if" block in the "parmetis.package". 
- If "USE_64_BIT_INDICES=ON", add extra pieces of codes in "${ORIG_DIR}/${PROJECT}/patches/parmetis-4.0.3-build.patch" to modify the IDXTYPEWIDTH & REALTYPEWIDTH.

# How Has This Been Tested?
- Tested the modified candi on Ubuntu desktop.

### CODE REVIEW

**Comment by tjhei** [comment]
Hi @Wendi-L , thank you for this fix! I checked and you are correct in that METIS has to be patched manually to switch to 64 bit indices as seen in spack: 
https://github.com/spack/spack/blob/8f5209063dbe97d08db61ebbbf06bf5d176275eb/var/spack/repos/builtin/packages/metis/package.py#L58-L60

Why do you also switch REALTYPEWIDTH? I am not sure this is necessary.

**Comment by Wendi-L** [comment]
Hi Timo,

Many thanks for your review. Yes, you are correct that modifying REALTYPEWIDTH is not necessary. Just changing IDXTYPEWIDTH should be sufficient.

May I know if I should close this pull request and submit another with IDXTYPEWIDTH modification only?


Best Regards

Wendi

**Comment by tjhei** [comment]
> May I know if I should close this pull request and submit another with IDXTYPEWIDTH modification only?

No, please leave the PR open. Can make the change, commit, and push to your repository again?

**Comment by Wendi-L** [comment]
> > May I know if I should close this pull request and submit another with IDXTYPEWIDTH modification only?
> 
> No, please leave the PR open. Can you make the change, commit, and push to your repository again?

Thanks, Timo. It has been done.

**Review by tjhei — APPROVED** [review]
I made a small modification (move patch into a file). Otherwise this is good to go. Thanks again.

**Comment by tjhei** [comment]
(cherry-picked to master)

**Pull request merged**
