### PR TITLE
Fix path to installed CMake files.

### PR DESCRIPTION
**Pull request by drwells**
Same as

https://github.com/IBAMR/autoibamr/pull/79

but for candi.

autoibamr is like candi but for ibamr instead of deal.II - candi works well enough that I just copied and pasted it and added and removed dependencies. Hence bug reports for autoibamr sometimes apply here too.

### CODE REVIEW

**Comment by drwells** [comment]
```C
Building openblas 0.3.13
getarch_2nd.c: In function ‘main’:
getarch_2nd.c:14:35: error: ‘SGEMM_DEFAULT_UNROLL_M’ undeclared (first use in this function); did you mean ‘SBGEMM_DEFAULT_UNROLL_M’?
   14 |     printf("SGEMM_UNROLL_M=%d\n", SGEMM_DEFAULT_UNROLL_M);
      |                                   ^~~~~~~~~~~~~~~~~~~~~~
      |                                   SBGEMM_DEFAULT_UNROLL_M
```
what?

**Comment by tjhei** [comment]
error might be fixed by #300

**Comment by tjhei** [comment]
I will merge because the error is unrelated.

**Comment by tjhei** [comment]
Oh, and thanks for the fix! :+1:

**Pull request merged**
